[package]
name = "rdml_leptos"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "An alternative templating macro for leptos"
repository = "https://github.com/zacklukem/rdml"
homepage = "https://github.com/zacklukem/rdml"
keywords = ["html", "macro", "leptos"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = "1.0.42"
rdml = { workspace = true }
syn = { workspace = true }

[dev-dependencies]
leptos = "0.8.15"
