[package]
name = "rdml"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.104"
syn = { version = "2.0.111", features = ["extra-traits", "full"] }

[dev-dependencies]
insta = "1.45.0"
